#!/bin/sh

mkdir -p /data/logs
DATE=`date +%Y-%m-%d:%H:%M:%S`

echo "###################"$DATE"###################" >> /data/logs/monthly.log
#同步股票历史数据。
/usr/local/bin/python3 /data/stock/job/download_pro_bar.py >> /data/logs/monthly.log

